### ISSUE TITLE
Add to packagist and release version

### ISSUE THREAD

**Issue by SilvanLaroo** [dmatthew/magento2-attribute-description#1]
Hi,

This extension looks great. Could you add it to packagist.org and release a stable version?

Thanks

**Comment by mageho** [comment]
+1

**Comment by Amadeco** [comment]
+1
keep up the good work

**Comment by dmatthew** [comment]
Thanks. Its been so long since I've looked at this. I'll work on it soon to make sure it still works and if it does I'll get it on Packagist.

**Comment by dmatthew** [comment]
I've added it to packagist: https://packagist.org/packages/dmatthew/magento2-attribute-description

**Comment by Amadeco** [comment]
Thank you, appreciated.

It will be easier to maintain on our website.
