### ISSUE TITLE
PHP 7.2, 7.3 is not supported

### ISSUE THREAD

**Issue by glevhen** [dmatthew/magento2-attribute-description#6]
I noticed that support of PHP 7.2 and PHP 7.2 was removed in https://github.com/dmatthew/magento2-attribute-description/commit/944f08593464d59332ae39dbf06c6e6786075185
Could you add it again?

**Comment by dmatthew** [comment]
Did you actually run into any issues installing it with PHP 7.2 or 7.3? The PHP requirement is `^7.1.0` which means anything greater than or equal to `7.1.0` but less than `8.0`. See the documentation for the `^` operator: https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by glevhen** [comment]
@dmatthew did you try to install your module using php 7.2?
`vendemo git:(VDS-143-update-235-p1) ✗ php -v
PHP 7.2.30 (cli) (built: Apr 24 2020 12:26:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies
➜  vendemo git:(VDS-143-update-235-p1) ✗ composer require dmatthew/magento2-attribute-description


  [InvalidArgumentException]
  Package dmatthew/magento2-attribute-description at version  has a PHP requirement incompatible with your PHP version (7.2.30)


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...`

**Comment by dmatthew** [comment]
I'll take another look.

**Comment by dmatthew** [comment]
@glevhen Whats your composer version?

**Comment by glevhen** [comment]
@dmatthew 
➜  vendemo git:(VDS-143-update-235-p1) ✗ composer -V
Composer version 1.9.2
![image](https://user-images.githubusercontent.com/16398798/82688105-f76b0180-9c60-11ea-90ce-22edb437ffee.png)

**Comment by dmatthew** [comment]
Hmm, its working for me on PHP 7.2.22 and composer 1.10.6.

**Comment by glevhen** [comment]
@dmatthew 
checked also on the staging composer 1.10.6 and PHP 7.2.31
`master vendemo2@wood:~/magento2$ composer -V
Composer version 1.10.6 2020-05-06 10:28:10
master vendemo2@wood:~/magento2$ php -v
PHP 7.2.31-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 14 2020 08:27:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.31-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
master vendemo2@wood:~/magento2$ composer require dmatthew/magento2-attribute-description
Warning from https://repo.packagist.com/vendic:
You are using a read-only authentication token, if you're running composer update, composer require, or composer install without a lock file, no new packages will be mirrored.


  [InvalidArgumentException]
  Package dmatthew/magento2-attribute-description at version  has a PHP requirement incompatible with your PHP version (7.2.31)


require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
`

**Comment by dmatthew** [comment]
It worked on a different server running PHP 7.2.31.

Can you post your composer.json file?

**Comment by dmatthew** [comment]
It would be helpful to show the result of `composer show -p` as well.

**Comment by glevhen** [comment]
@dmatthew I can install the module for clean magento 2.3.5-p1 installation for the same composer and php versions, so seems it's issue only for my custom project, will resolve it myself, so we can close the issue, thanks
